# Generated by Django 5.2.3 on 2025-07-11 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(default='new', on_delete=django.db.models.deletion.RESTRICT, related_name='statuses', to='webapp.taskstatus', verbose_name='Статус'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.CreateModel(
            name='TaskTypeRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_types', to='webapp.task')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_tasks', to='webapp.tasktype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='tasks', through='webapp.TaskTypeRelation', through_fields=('task', 'type'), to='webapp.tasktype', verbose_name='Типы'),
        ),
    ]
